import { AppData } from './types';

export const initialAppData: AppData = {
  locationName: 'La Bocana, Cantón Piñas, Provincia de El Oro, Ecuador',
  latitude: -3.6825,
  longitude: -79.6811,
  userIotApiKey: 'hc_live_bocana_77f4a9',
  weather: {
    temperature: 23.4,
    humidity: 78,
    windSpeed: 9.5,
    condition: 'Parcialmente nublado con brisa fresca de cordillera',
    lastUpdated: new Date().toISOString(),
  },
  tasks: [
    {
      id: 'tsk-01',
      title: 'Medición matutina de pH y EC en tanques',
      description: 'Verificar que el pH se encuentre entre 5.8 y 6.2 y EC entre 1.4 y 1.6 mS/cm',
      dueDate: new Date().toISOString().split('T')[0],
      priority: 'high',
      repeat: 'daily',
      completed: true,
      systemId: 'sys-dwc-01',
    },
    {
      id: 'tsk-02',
      title: 'Revisar nivel de agua y recarga de tanque',
      description: 'Asegurar al menos 45L en DWC y 35L en Torre vertical',
      dueDate: new Date().toISOString().split('T')[0],
      priority: 'medium',
      repeat: 'daily',
      completed: false,
      systemId: 'sys-dwc-01',
    },
    {
      id: 'tsk-03',
      title: 'Limpieza de filtros y bomba sumergible',
      description: 'Retirar bio-película y sedimentos del prefiltro de la torre vertical',
      dueDate: '2026-09-24',
      priority: 'medium',
      repeat: 'biweekly',
      completed: false,
      systemId: 'sys-vert-01',
    },
    {
      id: 'tsk-04',
      title: 'Calibración de electrodo de pH con solución buffer',
      description: 'Calibrar con amortiguador 4.01 y 7.00',
      dueDate: '2026-09-24',
      priority: 'high',
      repeat: 'biweekly',
      completed: false,
      systemId: 'sys-dwc-01',
    },
    {
      id: 'tsk-05',
      title: 'Cosecha estimada de lechugas Batavia',
      description: 'Corte limpio de base foliar y pesaje individual',
      dueDate: '2026-09-28',
      priority: 'high',
      repeat: 'none',
      completed: false,
      systemId: 'sys-dwc-01',
    },
  ],
  equipments: [
    {
      id: 'eq-01',
      name: 'Bomba Sumergible Atman 25W',
      type: 'Bomba de Agua',
      systemId: 'sys-vert-01',
      status: 'good',
      lastMaintenanceDate: '2026-09-10',
      nextMaintenanceDate: '2026-09-24',
      operatingHours: 720,
      notes: 'Impulsor magnético lubricado y prefiltro limpio',
    },
    {
      id: 'eq-02',
      name: 'Aireador Electromagnético Resun 4W',
      type: 'Bomba de Aire',
      systemId: 'sys-dwc-01',
      status: 'good',
      lastMaintenanceDate: '2026-09-08',
      nextMaintenanceDate: '2026-09-22',
      operatingHours: 1080,
      notes: 'Membrana de diafragma en óptimas condiciones',
    },
    {
      id: 'eq-03',
      name: 'Piedra Difusora Microperforada',
      type: 'Difusor',
      systemId: 'sys-dwc-01',
      status: 'good',
      lastMaintenanceDate: '2026-09-08',
      nextMaintenanceDate: '2026-09-22',
      operatingHours: 1080,
      notes: 'Descalcificada con solución ácida débil',
    },
    {
      id: 'eq-04',
      name: 'Sonda Electrodo pH Calibrada',
      type: 'Sensor / Sonda',
      systemId: 'sys-dwc-01',
      status: 'good',
      lastMaintenanceDate: '2026-09-10',
      nextMaintenanceDate: '2026-09-24',
      operatingHours: 1200,
      notes: 'Almacenada con solución KCl 3M cuando no está en inmersión',
    },
  ],
  nutrientRecords: [
    {
      id: 'nr-01',
      date: '2026-09-01T10:30:00.000Z',
      systemId: 'sys-dwc-01',
      waterVolumeLiters: 60,
      productId: 'nut-a-01',
      productName: 'HydroMax Solución A (Calcio & N)',
      doseApplied: 300,
      doseMl: 300,
      unit: 'ml',
      phBefore: 7.2,
      phAfter: 6.8,
      ecBefore: 0.2,
      ecAfter: 0.9,
      notes: 'Preparación solución inicial',
    },
    {
      id: 'nr-02',
      date: '2026-09-01T10:45:00.000Z',
      systemId: 'sys-dwc-01',
      waterVolumeLiters: 60,
      productId: 'nut-b-01',
      productName: 'HydroMax Solución B (Fósforo, K, Mg)',
      doseApplied: 300,
      doseMl: 300,
      unit: 'ml',
      phBefore: 6.8,
      phAfter: 6.5,
      ecBefore: 0.9,
      ecAfter: 1.4,
      notes: 'Incorporación Solución B homogeneizada',
    },
    {
      id: 'nr-03',
      date: '2026-09-01T11:00:00.000Z',
      systemId: 'sys-dwc-01',
      waterVolumeLiters: 60,
      productId: 'ph-down-01',
      productName: 'pH Down Regulador Ácido',
      doseApplied: 18,
      doseMl: 18,
      unit: 'ml',
      phBefore: 6.5,
      phAfter: 6.0,
      notes: 'Ajuste final a pH 6.0 óptimo',
    },
  ],
  location: {
    placeName: 'La Bocana, Piñas, El Oro, Ecuador',
    latitude: -3.6825,
    longitude: -79.6811,
    elevationMeters: 1024,
    notes: 'Invernadero protegido con malla antitrips y sombra al 35%. Clima subtropical húmedo de montaña.',
    currentWeather: {
      temperature: 23.4,
      tempMin: 18.2,
      tempMax: 26.8,
      humidity: 78,
      precipitationMm: 1.2,
      windSpeedKmh: 9.5,
      weatherCodeDescription: 'Parcialmente nublado con brisa fresca de cordillera',
      lastUpdated: new Date().toISOString(),
    },
    weatherHistory: [
      { date: '2026-09-09', tempExterior: 24.1, tempMin: 18.0, tempMax: 27.2, humidity: 76, rainMm: 0.0 },
      { date: '2026-09-10', tempExterior: 23.5, tempMin: 18.5, tempMax: 26.5, humidity: 80, rainMm: 3.5 },
      { date: '2026-09-11', tempExterior: 22.8, tempMin: 17.9, tempMax: 25.9, humidity: 84, rainMm: 8.2 },
      { date: '2026-09-12', tempExterior: 24.5, tempMin: 18.2, tempMax: 27.8, humidity: 72, rainMm: 0.0 },
      { date: '2026-09-13', tempExterior: 23.9, tempMin: 18.4, tempMax: 26.9, humidity: 75, rainMm: 0.8 },
      { date: '2026-09-14', tempExterior: 23.2, tempMin: 18.1, tempMax: 26.0, humidity: 81, rainMm: 2.1 },
      { date: '2026-09-15', tempExterior: 23.4, tempMin: 18.2, tempMax: 26.8, humidity: 78, rainMm: 1.2 },
    ],
  },
  systems: [
    {
      id: 'sys-dwc-01',
      name: 'Sistema DWC Raíz Flotante Tanque A',
      type: 'dwc',
      capacityLiters: 60,
      plantsCapacity: 24,
      currentPlantsCount: 22,
      location: 'Invernadero Principal - Mesa 1 (La Bocana)',
      installationDate: '2026-08-01',
      componentsList: [
        'Hielera isotérmica plástica 60L grado alimenticio',
        'Bomba de aire / Aireador electromagnético 4W',
        'Manguera de silicona 4mm grado acuícola',
        'Piedra difusora microperforada 10cm',
        'Plancha de espuma plast perforada',
        'Vasos de canastilla hidropónica 2 pulgadas',
        'Cubos de espuma fenólica Oasis',
      ],
      componentsDetail: {
        dwc: {
          hasAerator: true,
          aeratorModel: 'Resun Air-4000 4W Doble Salida',
          hose: true,
          diffuserStone: true,
          containerType: 'Hielera isotérmica con tapa sellada',
          cupsCount: 24,
          foamType: 'Espuma fenólica 2.5x2.5cm',
        },
      },
      photos: [
        'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=800&q=80',
      ],
      notes: 'Excelente oxigenación constante (DO > 6.8 mg/L). Temperatura del agua amortiguada por el aislamiento térmico.',
      status: 'active',
      currentWaterLevelLiters: 48,
      minWaterLevelLiters: 20,
    },
    {
      id: 'sys-vert-01',
      name: 'Torre Vertical Tubos PVC Torre 1',
      type: 'vertical_tubes',
      capacityLiters: 50,
      plantsCapacity: 36,
      currentPlantsCount: 32,
      location: 'Invernadero Principal - Sector Vertical A',
      installationDate: '2026-08-10',
      componentsList: [
        'Tubo PVC sanitario 4 pulgadas 2.2m perforado',
        'Bomba sumergible de agua 25W 1500 L/h altura 2m',
        'Manguera de polietileno 1/2 pulgada y derivaciones 4mm',
        'Vasos canastilla con ranuras laterales',
        'Espuma hidropónica cilíndrica de poliuretano',
        'Distribuidor superior tipo araña 4 puntos',
        'Tanque colector inferior 50L',
      ],
      componentsDetail: {
        vertical: {
          waterPump: true,
          waterPumpModel: 'Atman AT-104 25W 2000L/h',
          hoses: true,
          tubesCount: 3,
          cupsCount: 36,
          foamType: 'Poliuretano reticulado para hidroponía',
          distributionSystem: 'Flujo por gravedad con temporizador 15 min ON / 15 min OFF',
        },
      },
      photos: [
        'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=800&q=80',
      ],
      notes: 'Crecimiento foliar acelerado en frutillas y aromáticas. Limpieza quincenal de los orificios superiores.',
      status: 'active',
      currentWaterLevelLiters: 39,
      minWaterLevelLiters: 18,
    },
    {
      id: 'sys-aero-01',
      name: 'Sistema Aeropónico de Raíces Colgantes',
      type: 'aeroponics',
      capacityLiters: 40,
      plantsCapacity: 16,
      currentPlantsCount: 14,
      location: 'Laboratorio / Módulo Experimental La Bocana',
      installationDate: '2026-08-20',
      componentsList: [
        'Bomba diafragma alta presión 12V 80W 100 PSI',
        'Nebulizadores de latón micro-gotas 50 micras',
        'Cámara oscura de raíces con drenaje inclinado',
        'Temporizador cíclico digital por segundos',
        'Filtro de sedimentos 120 mesh previo a boquillas',
      ],
      componentsDetail: {
        aeroponic: {
          highPressurePump: true,
          nozzlesCount: 6,
          sprayFrequencyMin: 3,
          dropletCollector: true,
        },
      },
      photos: [
        'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
      ],
      notes: 'Máxima oxigenación radicular. Boquillas requieren agua filtrada para evitar incrustaciones salinas.',
      status: 'active',
      currentWaterLevelLiters: 32,
      minWaterLevelLiters: 15,
    },
  ],
  plants: [
    {
      id: 'plant-lec-001',
      code: 'LEC-001',
      species: 'Lechuga',
      variety: 'Batavia Crespa Verde',
      systemId: 'sys-dwc-01',
      position: 'Fila 1 - Vaso 01',
      seedingDate: '2026-08-22',
      germinationDate: '2026-08-25',
      transplantDate: '2026-09-01',
      estimatedHarvestDate: '2026-09-28',
      initialPhoto: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=600&q=80',
      observations: 'Planta madre testigo. Excelente desarrollo radicular blanco nacarado y cogollo denso.',
      status: 'healthy',
      currentHeightCm: 18.5,
      currentLeavesCount: 16,
      rootDevelopment: 'vigoroso',
      historyLogs: [
        {
          id: 'log-lec001-d1',
          date: '2026-09-01T09:00:00.000Z',
          dayNumber: 1,
          heightCm: 4.5,
          leavesCount: 4,
          rootDevelopment: 'inicial',
          plantSizeNotes: 'Plántula trasplantada con raíz asomando 2 cm del cubo de espuma',
          status: 'healthy',
          photo: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=600&q=80',
          waterMeasurements: { ph: 6.0, ec: 1.2, tds: 600, waterTemp: 21.0 },
          notes: 'Inicio de fase en raíz flotante con solución nutritiva al 50%.',
        },
        {
          id: 'log-lec001-d7',
          date: '2026-09-07T10:00:00.000Z',
          dayNumber: 7,
          heightCm: 8.2,
          leavesCount: 8,
          rootDevelopment: 'moderado',
          plantSizeNotes: 'Hojas verdaderas desplegadas, buena turgencia sin signos de estrés',
          status: 'healthy',
          photo: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=600&q=80',
          waterMeasurements: { ph: 6.1, ec: 1.4, tds: 700, waterTemp: 21.8 },
          notes: 'Raíces tocan la solución oxigenada vigorosamente.',
        },
        {
          id: 'log-lec001-d14',
          date: '2026-09-14T11:00:00.000Z',
          dayNumber: 14,
          heightCm: 14.0,
          leavesCount: 12,
          rootDevelopment: 'abundante',
          plantSizeNotes: 'Color verde brillante uniforme, borde rizado característico de Batavia',
          status: 'healthy',
          photo: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
          waterMeasurements: { ph: 6.0, ec: 1.5, tds: 750, waterTemp: 21.5 },
          notes: 'Solución nutritiva al 100%. Análisis de imagen confirma cero necrosis.',
          aiAnalysis: {
            analyzedAt: '2026-09-14T11:05:00.000Z',
            healthStatus: 'Saludable',
            overallCondition: 'Planta en estado vegetativo óptimo con alta densidad foliar y pigmentación adecuada.',
            leafEvaluation: {
              coloration: 'Verde esmeralda homogéneo sin manchas ni quemaduras de ápice (tip burn)',
              yellowing: false,
              spots: false,
              wilting: false,
              details: 'Láminas foliares turgentes con bordes rizados bien estructurados.',
            },
            rootEvaluation: 'Raíces visiblemente blancas, libres de algas u olores anóxicos.',
            possibleCauses: ['Manejo adecuado de EC y oxigenación continua en tanque isotérmico.'],
            generalRecommendations: [
              'Mantener nivel de solución nutritiva para evitar exposición prolongada de coronas.',
              'Continuar aireación constante para sostener el oxígeno disuelto > 6 mg/L.',
            ],
            recommendedWaterChecks: ['Monitorear pH diario entre 5.8 y 6.2', 'Verificar EC objetivo 1.4 - 1.6 mS/cm'],
            disclaimer: 'Evaluación visual basada en IA asistida. Verifique periódicamente la solución y raíz física.',
          },
        },
        {
          id: 'log-lec001-d15',
          date: '2026-09-15T09:30:00.000Z',
          dayNumber: 15,
          heightCm: 18.5,
          leavesCount: 16,
          rootDevelopment: 'vigoroso',
          plantSizeNotes: 'Crecimiento de 4.5 cm en 48 horas. Vigor sobresaliente.',
          status: 'healthy',
          photo: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
          waterMeasurements: { ph: 5.9, ec: 1.5, tds: 760, waterTemp: 21.2 },
          notes: 'Medición matutina registrada en sistema.',
        },
      ],
    },
    {
      id: 'plant-lec-002',
      code: 'LEC-002',
      species: 'Lechuga',
      variety: 'Romana Parris Island',
      systemId: 'sys-dwc-01',
      position: 'Fila 1 - Vaso 04',
      seedingDate: '2026-08-22',
      germinationDate: '2026-08-25',
      transplantDate: '2026-09-01',
      estimatedHarvestDate: '2026-10-02',
      initialPhoto: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=600&q=80',
      observations: 'Ligera clorosis internerval en dos hojas basales. Requiere seguimiento del pH y quelato de hierro.',
      status: 'needs_observation',
      currentHeightCm: 15.2,
      currentLeavesCount: 13,
      rootDevelopment: 'abundante',
      historyLogs: [
        {
          id: 'log-lec002-d1',
          date: '2026-09-01T09:00:00.000Z',
          dayNumber: 1,
          heightCm: 4.2,
          leavesCount: 4,
          rootDevelopment: 'inicial',
          status: 'healthy',
          notes: 'Trasplante normal',
        },
        {
          id: 'log-lec002-d14',
          date: '2026-09-14T11:30:00.000Z',
          dayNumber: 14,
          heightCm: 15.2,
          leavesCount: 13,
          rootDevelopment: 'abundante',
          status: 'needs_observation',
          photo: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&w=600&q=80',
          waterMeasurements: { ph: 6.6, ec: 1.3, tds: 650, waterTemp: 22.4 },
          notes: 'Se observó leve amarillamiento marginal. Se ajustó pH de 6.6 a 6.0.',
          aiAnalysis: {
            analyzedAt: '2026-09-14T11:32:00.000Z',
            healthStatus: 'Observación',
            overallCondition: 'Signos tempranos de clorosis ligera en borde foliar basal, posiblemente ligado a pH > 6.5 que reduce asimilación de microelementos.',
            leafEvaluation: {
              coloration: 'Tono verde claro con palidez en bordes inferiores',
              yellowing: true,
              spots: false,
              wilting: false,
              details: 'Sin necrosis activa ni manchas bacterianas/fúngicas aparentes.',
            },
            possibleCauses: [
              'Ligera deficiencia de asimilación de hierro o magnesio debido a elevación puntual del pH a 6.6.',
              'Consumo asimétrico de nutrientes en el sector del tanque.',
            ],
            generalRecommendations: [
              'Regular el pH a 5.8 - 6.0 con ácido fosfórico (pH Down).',
              'Verificar que el aireador distribuya burbujas de forma pareja hacia este vaso.',
            ],
            recommendedWaterChecks: ['Medir pH después de 4 horas del ajuste', 'Verificar EC de la solución'],
            disclaimer: 'Orientación agronómica preventiva generada por IA. No constituye certificación fitosanitaria.',
          },
        },
      ],
    },
    {
      id: 'plant-fre-001',
      code: 'FRE-001',
      species: 'Frutilla / Fresa',
      variety: 'Albión Refloreciente',
      systemId: 'sys-vert-01',
      position: 'Tubo 1 - Nivel 3 (Posición Norte)',
      seedingDate: '2026-07-15',
      germinationDate: '2026-07-22',
      transplantDate: '2026-08-12',
      estimatedHarvestDate: '2026-10-15',
      initialPhoto: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',
      observations: 'Primera floración con 3 botones florales bien formados y corona engrosada.',
      status: 'healthy',
      currentHeightCm: 16.0,
      currentLeavesCount: 14,
      rootDevelopment: 'vigoroso',
      historyLogs: [
        {
          id: 'log-fre001-d1',
          date: '2026-08-12T09:00:00.000Z',
          dayNumber: 1,
          heightCm: 7.0,
          leavesCount: 6,
          rootDevelopment: 'inicial',
          status: 'healthy',
          notes: 'Establecimiento en torre vertical con riego temporizado.',
        },
        {
          id: 'log-fre001-d20',
          date: '2026-09-01T10:00:00.000Z',
          dayNumber: 20,
          heightCm: 12.5,
          leavesCount: 10,
          rootDevelopment: 'abundante',
          status: 'healthy',
          notes: 'Desarrollo de peciolos firmes.',
        },
        {
          id: 'log-fre001-d34',
          date: '2026-09-15T08:45:00.000Z',
          dayNumber: 34,
          heightCm: 16.0,
          leavesCount: 14,
          rootDevelopment: 'vigoroso',
          status: 'healthy',
          waterMeasurements: { ph: 5.8, ec: 1.8, tds: 900, waterTemp: 21.0 },
          notes: 'Apertura de primeras flores. Solución formulada con mayor proporción de potasio.',
        },
      ],
    },
    {
      id: 'plant-alb-001',
      code: 'ALB-001',
      species: 'Albahaca',
      variety: 'Genovesa Gigante',
      systemId: 'sys-vert-01',
      position: 'Tubo 2 - Nivel 4 (Posición Sur)',
      seedingDate: '2026-08-10',
      germinationDate: '2026-08-14',
      transplantDate: '2026-08-25',
      estimatedHarvestDate: '2026-09-30',
      observations: 'Hojas gruesas muy aromáticas. Se realizó despunte apical para promover ramificación.',
      status: 'healthy',
      currentHeightCm: 22.0,
      currentLeavesCount: 28,
      rootDevelopment: 'vigoroso',
      historyLogs: [
        {
          id: 'log-alb-d1',
          date: '2026-08-25T10:00:00.000Z',
          dayNumber: 1,
          heightCm: 8.0,
          leavesCount: 8,
          rootDevelopment: 'moderado',
          status: 'healthy',
          notes: 'Trasplante a torre vertical.',
        },
        {
          id: 'log-alb-d21',
          date: '2026-09-15T11:00:00.000Z',
          dayNumber: 21,
          heightCm: 22.0,
          leavesCount: 28,
          rootDevelopment: 'vigoroso',
          status: 'healthy',
          notes: 'Excelente vigor con aroma intenso.',
        },
      ],
    },
  ],
  sensors: [
    {
      id: 'sens-ph-01',
      name: 'Sonda pH Digital Calibrada V2',
      type: 'ph',
      variable: 'pH de la Solución Nutritiva',
      unit: 'pH',
      systemId: 'sys-dwc-01',
      calibrationDate: '2026-09-10',
      status: 'active',
      minIdeal: 5.6,
      maxIdeal: 6.4,
      source: 'manual',
    },
    {
      id: 'sens-ec-01',
      name: 'Medidor de Conductividad Eléctrica EC/TDS',
      type: 'ec',
      variable: 'Conductividad Eléctrica (EC)',
      unit: 'mS/cm',
      systemId: 'sys-dwc-01',
      calibrationDate: '2026-09-10',
      status: 'active',
      minIdeal: 1.2,
      maxIdeal: 1.8,
      source: 'manual',
    },
    {
      id: 'sens-wtemp-01',
      name: 'Sonda Sumergible DS18B20 Temp Agua',
      type: 'water_temp',
      variable: 'Temperatura del Agua de Raíz',
      unit: '°C',
      systemId: 'sys-dwc-01',
      calibrationDate: '2026-08-01',
      status: 'active',
      minIdeal: 18.0,
      maxIdeal: 23.5,
      source: 'manual',
    },
    {
      id: 'sens-do-01',
      name: 'Sensor Óptico de Oxígeno Disuelto DO',
      type: 'dissolved_oxygen',
      variable: 'Oxígeno Disuelto',
      unit: 'mg/L',
      systemId: 'sys-dwc-01',
      calibrationDate: '2026-09-01',
      status: 'active',
      minIdeal: 6.0,
      maxIdeal: 9.0,
      source: 'manual',
    },
    {
      id: 'sens-wlevel-01',
      name: 'Sensor Ultrasónico Nivel Tanque DWC',
      type: 'water_level',
      variable: 'Volumen de Agua en Tanque',
      unit: 'Litros',
      systemId: 'sys-dwc-01',
      calibrationDate: '2026-08-01',
      status: 'active',
      minIdeal: 25.0,
      maxIdeal: 60.0,
      source: 'manual',
    },
    {
      id: 'sens-dht-01',
      name: 'Sensor Ambiental DHT22 Invernadero',
      type: 'ambient_temp',
      variable: 'Temperatura Ambiental La Bocana',
      unit: '°C',
      systemId: 'sys-dwc-01',
      calibrationDate: '2026-08-15',
      status: 'active',
      minIdeal: 18.0,
      maxIdeal: 28.0,
      source: 'manual',
    },
  ],
  measurements: [
    { id: 'm-01', timestamp: '2026-09-14T08:00:00.000Z', systemId: 'sys-dwc-01', sensorType: 'ph', value: 6.1, unit: 'pH', source: 'manual', notes: 'Medición matutina' },
    { id: 'm-02', timestamp: '2026-09-14T08:00:00.000Z', systemId: 'sys-dwc-01', sensorType: 'ec', value: 1.45, unit: 'mS/cm', source: 'manual' },
    { id: 'm-03', timestamp: '2026-09-14T08:00:00.000Z', systemId: 'sys-dwc-01', sensorType: 'tds', value: 725, unit: 'ppm', source: 'manual' },
    { id: 'm-04', timestamp: '2026-09-14T08:00:00.000Z', systemId: 'sys-dwc-01', sensorType: 'water_temp', value: 20.8, unit: '°C', source: 'manual' },
    { id: 'm-05', timestamp: '2026-09-14T08:00:00.000Z', systemId: 'sys-dwc-01', sensorType: 'dissolved_oxygen', value: 7.2, unit: 'mg/L', source: 'manual' },
    { id: 'm-06', timestamp: '2026-09-14T08:00:00.000Z', systemId: 'sys-dwc-01', sensorType: 'water_level', value: 50.0, unit: 'L', source: 'manual' },

    { id: 'm-07', timestamp: '2026-09-14T14:30:00.000Z', systemId: 'sys-dwc-01', sensorType: 'ph', value: 6.4, unit: 'pH', source: 'manual', notes: 'Ligera subida tras hora de calor' },
    { id: 'm-08', timestamp: '2026-09-14T14:30:00.000Z', systemId: 'sys-dwc-01', sensorType: 'ec', value: 1.52, unit: 'mS/cm', source: 'manual' },
    { id: 'm-09', timestamp: '2026-09-14T14:30:00.000Z', systemId: 'sys-dwc-01', sensorType: 'water_temp', value: 22.4, unit: '°C', source: 'manual' },
    { id: 'm-10', timestamp: '2026-09-14T14:30:00.000Z', systemId: 'sys-dwc-01', sensorType: 'dissolved_oxygen', value: 6.8, unit: 'mg/L', source: 'manual' },

    { id: 'm-11', timestamp: '2026-09-15T08:15:00.000Z', systemId: 'sys-dwc-01', sensorType: 'ph', value: 5.95, unit: 'pH', source: 'manual', notes: 'pH estabilizado' },
    { id: 'm-12', timestamp: '2026-09-15T08:15:00.000Z', systemId: 'sys-dwc-01', sensorType: 'ec', value: 1.48, unit: 'mS/cm', source: 'manual' },
    { id: 'm-13', timestamp: '2026-09-15T08:15:00.000Z', systemId: 'sys-dwc-01', sensorType: 'tds', value: 740, unit: 'ppm', source: 'manual' },
    { id: 'm-14', timestamp: '2026-09-15T08:15:00.000Z', systemId: 'sys-dwc-01', sensorType: 'water_temp', value: 21.2, unit: '°C', source: 'manual' },
    { id: 'm-15', timestamp: '2026-09-15T08:15:00.000Z', systemId: 'sys-dwc-01', sensorType: 'dissolved_oxygen', value: 7.4, unit: 'mg/L', source: 'manual' },
    { id: 'm-16', timestamp: '2026-09-15T08:15:00.000Z', systemId: 'sys-dwc-01', sensorType: 'water_level', value: 48.0, unit: 'L', source: 'manual', notes: 'Consumo neto 2L en 24h' },
  ],
  forageLots: [
    {
      id: 'forage-001',
      code: 'FOR-001',
      seedType: 'Maíz Criollo Amarillo Seleccionado',
      seedAmountKg: 1.2,
      initialWeightKg: 1.2,
      startDate: '2026-09-09',
      germinationDate: '2026-09-11',
      trayId: 'Bandeja Forrajera 01 (60x40cm)',
      temperatureAvg: 23.1,
      humidityAvg: 82,
      phAvg: 6.2,
      ecAvg: 0.8,
      currentHeightCm: 14.5,
      currentWeightKg: 6.8,
      yieldRatio: 5.66,
      photos: [
        'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=800&q=80',
      ],
      notes: 'Excelente germinación al 96%. Tapiz radicular entrelazado limpio y blanco, sin hongos.',
      status: 'active',
      growthDays: [
        { day: 1, date: '2026-09-09', heightCm: 0.0, weightKg: 1.2, notes: 'Remojo de semilla 24h con solución ligera de cal apagada y enjuague.' },
        { day: 2, date: '2026-09-10', heightCm: 0.5, weightKg: 1.6, notes: 'Fase de oscuridad. Emergencia de radículas.' },
        { day: 3, date: '2026-09-11', heightCm: 2.5, weightKg: 2.4, notes: 'Germinación uniforme, pase a luz difusa y microaspersión.' },
        { day: 4, date: '2026-09-12', heightCm: 5.5, weightKg: 3.5, notes: 'Verdeo intenso de coleóptilos.' },
        { day: 5, date: '2026-09-13', heightCm: 9.8, weightKg: 4.9, notes: 'Desarrollo vigoroso de primeras hojas.' },
        { day: 6, date: '2026-09-14', heightCm: 12.2, weightKg: 5.9, notes: 'Manto radicular denso y esponjoso.' },
        { day: 7, date: '2026-09-15', heightCm: 14.5, weightKg: 6.8, notes: 'Día 7: listo para cosecha o alimentación animal al día 10-12.' },
      ],
    },
  ],
  waterRefills: [
    { id: 'wr-01', date: '2026-09-01T10:00:00.000Z', systemId: 'sys-dwc-01', litersAdded: 60, notes: 'Llenado inicial con solución nutritiva fresca' },
    { id: 'wr-02', date: '2026-09-08T15:00:00.000Z', systemId: 'sys-dwc-01', litersAdded: 15, notes: 'Reposición de agua declorada con media dosis de nutrientes' },
    { id: 'wr-03', date: '2026-09-13T16:00:00.000Z', systemId: 'sys-dwc-01', litersAdded: 12, notes: 'Reposición tras días soleados' },
  ],
  nutrientProducts: [
    {
      id: 'nut-a-01',
      name: 'HydroMax Solución A (Calcio & Nitrógeno)',
      brand: 'AgroHydro Ecuador',
      type: 'nutrient_a',
      composition: 'Nitrato de Calcio 15.5% N, 19% Ca + Quelato de Hierro EDDHA 6%',
      concentration: 'Concentrado líquido 10x',
      recommendedDosePerLiter: 5,
      unit: 'ml',
      instructions: 'Diluir siempre primero en agua antes de agregar la Solución B para evitar precipitación de fosfato de calcio.',
    },
    {
      id: 'nut-b-01',
      name: 'HydroMax Solución B (Fósforo, Potasio & Magnesio)',
      brand: 'AgroHydro Ecuador',
      type: 'nutrient_b',
      composition: 'Fosfato Monopotásico (MKP), Sulfato de Magnesio heptahidratado + Micronutrientes (B, Zn, Mn, Cu, Mo)',
      concentration: 'Concentrado líquido 10x',
      recommendedDosePerLiter: 5,
      unit: 'ml',
      instructions: 'Agregar al tanque únicamente tras haber homogeneizado bien la Solución A.',
    },
    {
      id: 'nut-c-01',
      name: 'HydroMax Solución C (Refuerzo Potasio Floración/Engorde)',
      brand: 'AgroHydro Ecuador',
      type: 'nutrient_c',
      composition: 'Sulfato de Potasio soluble al 52% K2O, 18% S',
      concentration: 'Polvo soluble / concentrado',
      recommendedDosePerLiter: 2,
      unit: 'ml',
      instructions: 'Aplicar durante floración en frutillas y tomates, o refuerzo en lechugas maduras.',
    },
    {
      id: 'ph-down-01',
      name: 'pH Down Regulador Ácido',
      brand: 'HydroControl Lab',
      type: 'ph_down',
      composition: 'Ácido fosfórico al 20% alimentario',
      concentration: '20% v/v',
      recommendedDosePerLiter: 0.3,
      unit: 'ml',
      instructions: 'Dosificar gota a gota o en jeringa milimétrica. Esperar 15 minutos con recirculación antes de re-medir.',
    },
    {
      id: 'ph-up-01',
      name: 'pH Up Regulador Alcalino',
      brand: 'HydroControl Lab',
      type: 'ph_up',
      composition: 'Hidróxido de Potasio (KOH) al 10%',
      concentration: '10% p/v',
      recommendedDosePerLiter: 0.2,
      unit: 'ml',
      instructions: 'Aumenta el pH aportando potasio libre de sodio.',
    },
  ],
  nutrientLogs: [
    {
      id: 'nlog-01',
      date: '2026-09-01T10:30:00.000Z',
      systemId: 'sys-dwc-01',
      waterVolumeLiters: 60,
      productId: 'nut-a-01',
      productName: 'HydroMax Solución A',
      doseApplied: 300,
      unit: 'ml',
      phBefore: 7.2,
      phAfter: 6.8,
      ecBefore: 0.2,
      ecAfter: 0.9,
      tdsBefore: 100,
      tdsAfter: 450,
      notes: 'Preparación solución inicial tanque DWC.',
    },
    {
      id: 'nlog-02',
      date: '2026-09-01T10:45:00.000Z',
      systemId: 'sys-dwc-01',
      waterVolumeLiters: 60,
      productId: 'nut-b-01',
      productName: 'HydroMax Solución B',
      doseApplied: 300,
      unit: 'ml',
      phBefore: 6.8,
      phAfter: 6.5,
      ecBefore: 0.9,
      ecAfter: 1.4,
      tdsBefore: 450,
      tdsAfter: 700,
      notes: 'Incorporación de Solución B homogeneizada.',
    },
    {
      id: 'nlog-03',
      date: '2026-09-01T11:00:00.000Z',
      systemId: 'sys-dwc-01',
      waterVolumeLiters: 60,
      productId: 'ph-down-01',
      productName: 'pH Down Regulador Ácido',
      doseApplied: 18,
      unit: 'ml',
      phBefore: 6.5,
      phAfter: 6.0,
      notes: 'Ajuste final a pH óptimo 6.0 (reducción de 0.5 puntos con 0.3 ml/L).',
    },
  ],
  maintenanceLogs: [
    {
      id: 'maint-01',
      systemId: 'sys-dwc-01',
      systemName: 'Sistema DWC Raíz Flotante Tanque A',
      equipmentItem: 'Piedra Difusora y Manguera',
      actionType: 'limpieza',
      performedAt: '2026-09-08T16:00:00.000Z',
      nextScheduledDate: '2026-09-22',
      technician: 'Operador Principal',
      notes: 'Desincrustación de sales con agua tibia y vinagre blanco. Caudal de burbujas restaurado al 100%.',
      status: 'completed',
    },
    {
      id: 'maint-02',
      systemId: 'sys-vert-01',
      systemName: 'Torre Vertical Tubos PVC 1',
      equipmentItem: 'Bomba Sumergible Atman 25W',
      actionType: 'revision_bomba',
      performedAt: '2026-09-10T14:00:00.000Z',
      nextScheduledDate: '2026-09-24',
      technician: 'Operador Principal',
      notes: 'Inspección de impulsor magnético y retiro de biopelícula en prefiltro.',
      status: 'completed',
    },
    {
      id: 'maint-03',
      systemId: 'sys-dwc-01',
      systemName: 'Sistema DWC Raíz Flotante Tanque A',
      equipmentItem: 'Electrodo Sonda pH',
      actionType: 'calibracion_sensores',
      performedAt: '2026-09-10T11:00:00.000Z',
      nextScheduledDate: '2026-09-24',
      technician: 'Operador Principal',
      notes: 'Calibración en 2 puntos con soluciones amortiguadoras pH 4.01 y 7.00. Pendiente 98.4%.',
      status: 'completed',
    },
    {
      id: 'maint-04',
      systemId: 'sys-dwc-01',
      systemName: 'Sistema DWC Raíz Flotante Tanque A',
      equipmentItem: 'Agua del Tanque',
      actionType: 'cambio_agua',
      performedAt: '2026-09-01T09:00:00.000Z',
      nextScheduledDate: '2026-09-22',
      technician: 'Operador Principal',
      notes: 'Renovación completa programada cada 21 días.',
      status: 'scheduled',
    },
  ],
  calendarTasks: [
    {
      id: 'cal-01',
      title: 'Medir pH y EC de la solución nutritiva',
      category: 'medicion',
      date: '2026-09-15',
      isRecurring: true,
      recurrencePeriod: 'daily',
      completed: true,
      notes: 'Verificar ambos tanques (DWC y Vertical).',
    },
    {
      id: 'cal-02',
      title: 'Revisión visual de raíces en DWC y boquillas aeropónicas',
      category: 'mantenimiento',
      date: '2026-09-16',
      isRecurring: true,
      recurrencePeriod: 'weekly',
      completed: false,
      notes: 'Levantar plancha y verificar coloración blanca y oxigenación.',
    },
    {
      id: 'cal-03',
      title: 'Siembra de nuevo lote de forraje hidroeléctrico FOR-002',
      category: 'siembra',
      date: '2026-09-17',
      isRecurring: false,
      completed: false,
      notes: '1.5 kg de maíz criollo remojado.',
    },
    {
      id: 'cal-04',
      title: 'Calibración quincenal de sondas pH y EC',
      category: 'calibracion',
      date: '2026-09-24',
      isRecurring: true,
      recurrencePeriod: 'biweekly',
      completed: false,
      notes: 'Usar soluciones buffer pH 4.01 y 7.00 y EC 1413 uS/cm.',
    },
    {
      id: 'cal-05',
      title: 'Cosecha estimada lote lechuga LEC-001 y adyacentes',
      category: 'cosecha',
      date: '2026-09-28',
      isRecurring: false,
      completed: false,
      notes: 'Peso estimado > 280g por pieza.',
    },
  ],
  alerts: [
    {
      id: 'al-01',
      severity: 'observation',
      title: 'Planta LEC-002: Observación de color foliar',
      message: 'Ligera palidez en bordes de hojas basales registrada en la última inspección visual.',
      systemId: 'sys-dwc-01',
      systemName: 'Sistema DWC Raíz Flotante Tanque A',
      plantId: 'plant-lec-002',
      parameter: 'Salud Foliar',
      value: 'Observación',
      idealRange: 'Saludable',
      timestamp: '2026-09-14T11:32:00.000Z',
      acknowledged: false,
    },
    {
      id: 'al-02',
      severity: 'normal',
      title: 'Oxígeno disuelto en rango óptimo',
      message: 'Nivel sostenido en 7.4 mg/L en DWC gracias al aireador continuo de 4W y piedra difusora.',
      systemId: 'sys-dwc-01',
      systemName: 'Sistema DWC Raíz Flotante Tanque A',
      parameter: 'Oxígeno Disuelto (DO)',
      value: 7.4,
      idealRange: '6.0 - 9.0 mg/L',
      timestamp: '2026-09-15T08:15:00.000Z',
      acknowledged: true,
    },
  ],
  photos: [
    {
      id: 'photo-01',
      url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
      timestamp: '2026-09-14T11:00:00.000Z',
      targetType: 'plant',
      targetId: 'plant-lec-001',
      targetCode: 'LEC-001',
      targetName: 'Lechuga Batavia Crespa - Vaso 1',
      notes: 'Fotografía para análisis fitosanitario con IA Gemini. Día 14 de cultivo.',
      aiAnalysis: {
        analyzedAt: '2026-09-14T11:05:00.000Z',
        healthStatus: 'Saludable',
        overallCondition: 'Planta en estado vegetativo óptimo con alta densidad foliar y pigmentación adecuada.',
        leafEvaluation: {
          coloration: 'Verde esmeralda homogéneo sin manchas ni quemaduras de ápice (tip burn)',
          yellowing: false,
          spots: false,
          wilting: false,
          details: 'Láminas foliares turgentes con bordes rizados bien estructurados.',
        },
        rootEvaluation: 'Raíces visiblemente blancas, libres de algas u olores anóxicos.',
        possibleCauses: ['Manejo adecuado de EC y oxigenación continua en tanque isotérmico.'],
        generalRecommendations: [
          'Mantener nivel de solución nutritiva para evitar exposición prolongada de coronas.',
          'Continuar aireación constante para sostener el oxígeno disuelto > 6 mg/L.',
        ],
        recommendedWaterChecks: ['Monitorear pH diario entre 5.8 y 6.2', 'Verificar EC objetivo 1.4 - 1.6 mS/cm'],
        disclaimer: 'Evaluación visual asistida por IA Gemini. Verifique periódicamente la raíz física.',
      },
    },
    {
      id: 'photo-02',
      url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=800&q=80',
      timestamp: '2026-09-14T09:00:00.000Z',
      targetType: 'forage',
      targetId: 'forage-001',
      targetCode: 'FOR-001',
      targetName: 'Forraje Verde Maíz Criollo - Bandeja 01',
      notes: 'Evolución de altura en día 6 de germinación (12.2 cm).',
    },
  ],
};

export const initialData = initialAppData;
